apiVersion: v1
kind: Pod
metadata:
  name: home-assistant-volume
  namespace: home-assistant
spec:
  containers:
  - name: home-assistant-0
    image: homeassistant/home-assistant:2023.10.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
