apiVersion: v1
data:
  index.html: |
    <html>
    <head>
    <style>
      body { 
            background-color: orange;
          }
    </style>
      <title>Hello World!</title>
    </head>
    <body>Hello World!</body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-hello-world-configmap
  namespace: apps
