---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-hello-world
  name: spring-hello-world
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-hello-world
  type: ClusterIP
status:
  loadBalancer: {}
