apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular-hello-world-app
  name: angular-hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-hello-world-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular-hello-world-app
    spec:
      containers:
      - image: jacflesher/angular-hello-world:v0.1
        name: angular-hello-world
        imagePullPolicy: Always
        resources: {}
status: {}
