- hosts: "*"
  become: yes
  tasks:
    - name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
      ansible.builtin.shell: w > /tmp/w_test.txt; pwd >> /tmp/w_test.txt
      args:
        executable: /bin/bash
