apiVersion: v1
kind: Pod
metadata:
  name: python-ubi9-pod
spec:
  volumes:
    - name: app-source
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: python-ubi9-container
      image: registry.access.redhat.com/ubi9/python-311:latest
      volumeMounts:
        - mountPath: /opt/app-root/src
          name: app-source
      command: ["python3"]
      args: ["app.py"]
