apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  cidr-default: 192.168.0.200/29                      # CIDR-based IP range for use in the default Namespace
  range-development: 192.168.0.210-192.168.0.219      # Range-based IP range for use in the development Namespace
  cidr-finance: 192.168.0.220/29,192.168.0.230/29     # Multiple CIDR-based ranges for use in the finance Namespace
  cidr-global: 192.168.0.240/29                       # CIDR-based range which can be used in any Namespace
