apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: blackbox
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: 9115
#  - name: https
#    port: 443
#    protocol: TCP
#    targetPort: 9115
  selector:
    app: blackbox-exporter
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.240
    - ip: 192.168.0.241
    - ip: 192.168.0.242
    - ip: 192.168.0.243

