apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  namespace: apps
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-api-key-secret
    solvers:
    - dns01:
        cloudflare:
          email: jac.flesher@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
