apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: <path:projects/691569880619/secrets/cloudflare-api-key-secret#cloudflare-api-key-secret>
